import { useMemo } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { catalog, type Command } from "@/lib/catalog";
import { Button } from "@/components/ui/button";
import { Heart, History, ArrowLeft, Command as CommandIcon } from "lucide-react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";

function read(key: string) { try { return JSON.parse(localStorage.getItem(key) || "[]") as string[]; } catch { return []; } }
function adaptServerCommand(row: any): Command { const local = catalog.find((item) => item.command === row.slashCommand || item.id === row.slug); return local || { id: row.slug, command: row.slashCommand, name: row.name, description: row.description, category: row.category, subcategory: row.subcategory, outputType: row.outputType, platform: row.platform, objective: row.objective, difficulty: row.difficulty, featured: row.featured, tags: String(row.tags || "").split(",").filter(Boolean), template: row.promptTemplate, placeholders: [] }; }
export default function PersonalPage() {
  const { user } = useAuth(); const [, navigate] = useLocation();
  const serverFavorites = trpc.personal.favorites.useQuery(undefined, { enabled: Boolean(user) });
  const serverRecent = trpc.personal.recent.useQuery(undefined, { enabled: Boolean(user) });
  const favoriteIds = useMemo(() => read("cc-favorites"), []); const recentIds = useMemo(() => read("cc-recent"), []);
  const favorites = serverFavorites.data?.length ? serverFavorites.data.map((row) => adaptServerCommand(row.command)) : catalog.filter((item) => favoriteIds.includes(item.id));
  const recent = serverRecent.data?.length ? serverRecent.data.map((row) => adaptServerCommand(row.command)) : recentIds.map((id) => catalog.find((item) => item.id === id)).filter(Boolean);
  if (!user) return <div className="grid min-h-screen place-items-center bg-[#fbfbfd] p-5"><div className="max-w-sm text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-violet-100 text-violet-600"><Heart /></div><h1 className="font-display mt-5 text-2xl font-semibold">Sua coleção pessoal</h1><p className="mt-2 text-sm leading-6 text-black/50">Entre para salvar favoritos e consultar os comandos usados recentemente.</p><Button onClick={() => startLogin()} className="mt-6 rounded-xl bg-[#17151f]">Entrar com sua conta</Button></div></div>;
  return <div className="min-h-screen bg-[#fbfbfd]"><header className="border-b border-black/[0.06] bg-white"><div className="container flex h-16 items-center justify-between"><button onClick={() => navigate("/")} className="flex items-center gap-2 text-sm text-black/55"><ArrowLeft className="h-4 w-4" /> Catálogo</button><span className="flex items-center gap-2 font-display font-semibold"><CommandIcon className="h-4 w-4" /> Minha coleção</span><span className="text-xs text-black/45">{user.name}</span></div></header><main className="container py-12"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-600">Área pessoal</p><h1 className="font-display mt-2 text-4xl font-semibold tracking-[-0.05em]">Seus comandos, no seu ritmo.</h1></div><section className="mt-10"><div className="flex items-center gap-2"><Heart className="h-5 w-5 text-rose-500" /><h2 className="font-display text-xl font-semibold">Favoritos</h2><span className="text-sm text-black/35">{favorites.length}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{favorites.length ? favorites.map((item) => <CommandTile key={item.id} item={item} onOpen={() => navigate(`/comandos/${item.id}`)} />) : <Empty text="Você ainda não salvou nenhum comando." />}</div></section><section className="mt-12"><div className="flex items-center gap-2"><History className="h-5 w-5 text-violet-600" /><h2 className="font-display text-xl font-semibold">Usados recentemente</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{recent.length ? recent.map((item) => item && <CommandTile key={item.id} item={item} onOpen={() => navigate(`/comandos/${item.id}`)} />) : <Empty text="Seus comandos recentes aparecerão aqui." />}</div></section></main></div>;
}
function CommandTile({ item, onOpen }: { item: (typeof catalog)[number]; onOpen: () => void }) { return <button onClick={onOpen} className="rounded-2xl border border-black/[0.08] bg-white p-4 text-left hover:-translate-y-0.5 hover:shadow-lg"><span className="font-mono text-xs text-violet-600">{item.command}</span><h3 className="mt-2 font-display font-semibold">{item.name}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-black/45">{item.description}</p></button>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-black/15 p-8 text-sm text-black/45">{text}</div>; }
