import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { getDb } from "./db";
import { commands, favorites, usages, imports, placeholders } from "../drizzle/schema";
import { and, desc, eq, like, or } from "drizzle-orm";
import { z } from "zod";

const commandInput = z.object({ slug: z.string(), slashCommand: z.string(), name: z.string(), description: z.string(), category: z.enum(["PENSAR", "ESCREVER", "CRIAR", "CRESCER"]), subcategory: z.string(), objective: z.string(), outputType: z.string(), platform: z.string(), promptTemplate: z.string(), tags: z.string(), difficulty: z.string(), featured: z.boolean().default(false) });
const importCommand = commandInput.extend({ placeholders: z.array(z.object({ name: z.string(), label: z.string(), type: z.string(), required: z.boolean().default(true), options: z.array(z.string()).default([]), defaultValue: z.string().optional() })).default([]) });

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(({ ctx }) => ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const options = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...options, maxAge: -1 }); return { success: true } as const; }),
  }),
  catalog: router({
    search: publicProcedure.input(z.object({ query: z.string().optional(), category: z.string().optional(), outputType: z.string().optional(), platform: z.string().optional(), objective: z.string().optional(), limit: z.number().max(100).default(50) })).query(async ({ input }) => { const db = await getDb(); if (!db) return []; const filters = []; if (input.query) filters.push(or(like(commands.name, `%${input.query}%`), like(commands.slashCommand, `%${input.query}%`), like(commands.description, `%${input.query}%`))); if (input.category && input.category !== "TODAS") filters.push(eq(commands.category, input.category as "PENSAR")); if (input.outputType && input.outputType !== "TODOS") filters.push(eq(commands.outputType, input.outputType)); if (input.platform && input.platform !== "TODAS") filters.push(eq(commands.platform, input.platform)); if (input.objective && input.objective !== "TODOS") filters.push(eq(commands.objective, input.objective)); filters.push(eq(commands.active, true)); return db.select().from(commands).where(and(...filters)).limit(input.limit); }),
    bySlug: publicProcedure.input(z.object({ slug: z.string() })).query(async ({ input }) => { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(commands).where(and(eq(commands.slug, input.slug), eq(commands.active, true))).limit(1); return rows[0]; }),
  }),
  personal: router({
    favorites: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select({ favorite: favorites, command: commands }).from(favorites).innerJoin(commands, eq(favorites.commandId, commands.id)).where(eq(favorites.userId, ctx.user.id)); }),
    recent: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; return db.select({ usage: usages, command: commands }).from(usages).innerJoin(commands, eq(usages.commandId, commands.id)).where(eq(usages.userId, ctx.user.id)).orderBy(desc(usages.createdAt)).limit(20); }),
    toggleFavorite: protectedProcedure.input(z.object({ commandSlug: z.string() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) return { saved: false }; const command = await db.select({ id: commands.id }).from(commands).where(eq(commands.slug, input.commandSlug)).limit(1); if (!command[0]) return { saved: false }; const existing = await db.select().from(favorites).where(and(eq(favorites.userId, ctx.user.id), eq(favorites.commandId, command[0].id))).limit(1); if (existing.length) { await db.delete(favorites).where(eq(favorites.id, existing[0].id)); return { saved: false }; } await db.insert(favorites).values({ userId: ctx.user.id, commandId: command[0].id }); return { saved: true }; }),
    recordUsage: protectedProcedure.input(z.object({ commandSlug: z.string() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (db) { const command = await db.select({ id: commands.id }).from(commands).where(eq(commands.slug, input.commandSlug)).limit(1); if (command[0]) await db.insert(usages).values({ userId: ctx.user.id, commandId: command[0].id }); } return { success: true }; }),
  }),
  admin: router({
    list: adminProcedure.input(z.object({ query: z.string().optional(), limit: z.number().max(100).default(100) })).query(async ({ input }) => { const db = await getDb(); if (!db) return []; const filter = input.query ? or(like(commands.name, `%${input.query}%`), like(commands.slashCommand, `%${input.query}%`)) : undefined; return db.select().from(commands).where(filter).orderBy(desc(commands.updatedAt)).limit(input.limit); }),
    create: adminProcedure.input(commandInput).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.insert(commands).values({ ...input, active: true }); return { success: true }; }),
    update: adminProcedure.input(z.object({ slug: z.string(), data: commandInput.partial() })).mutation(async ({ input }) => { const db = await getDb(); if (db) await db.update(commands).set(input.data).where(eq(commands.slug, input.slug)); return { success: true }; }),
    remove: adminProcedure.input(z.object({ slug: z.string() })).mutation(async ({ input }) => { const db = await getDb(); if (db) { const row = await db.select({ id: commands.id }).from(commands).where(eq(commands.slug, input.slug)).limit(1); if (row[0]) { await db.delete(placeholders).where(eq(placeholders.commandId, row[0].id)); await db.delete(commands).where(eq(commands.id, row[0].id)); } } return { success: true }; }),
    setFeatured: adminProcedure.input(z.object({ slug: z.string(), featured: z.boolean() })).mutation(async ({ input }) => { const db = await getDb(); if (db) await db.update(commands).set({ featured: input.featured }).where(eq(commands.slug, input.slug)); return { success: true }; }),
    deactivate: adminProcedure.input(z.object({ slug: z.string(), active: z.boolean() })).mutation(async ({ input }) => { const db = await getDb(); if (db) await db.update(commands).set({ active: input.active }).where(eq(commands.slug, input.slug)); return { success: true }; }),
    registerImport: adminProcedure.input(z.object({ filename: z.string(), format: z.enum(["json", "csv"]), importedCount: z.number().int().min(0) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (db) await db.insert(imports).values({ userId: ctx.user.id, ...input }); return { success: true }; }),
    importCommands: adminProcedure.input(z.object({ filename: z.string(), format: z.enum(["json", "csv"]), commands: z.array(importCommand).max(1000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); let count = 0; const conflicts: string[] = []; for (const item of input.commands) { const { placeholders: fields, ...command } = item; try { const slugRow = await db.select({ id: commands.id, slashCommand: commands.slashCommand }).from(commands).where(eq(commands.slug, command.slug)).limit(1); const slashRow = await db.select({ id: commands.id, slug: commands.slug }).from(commands).where(eq(commands.slashCommand, command.slashCommand)).limit(1); if (slugRow[0] && slashRow[0] && slugRow[0].id !== slashRow[0].id) { conflicts.push(`${command.slug}: slug e slashCommand pertencem a registros diferentes`); continue; } let commandId = slugRow[0]?.id || slashRow[0]?.id; if (commandId) { await db.update(commands).set({ ...command, active: true }).where(eq(commands.id, commandId)); await db.delete(placeholders).where(eq(placeholders.commandId, commandId)); } else { const inserted = await db.insert(commands).values({ ...command, active: true }); commandId = Number(inserted[0].insertId); } if (fields.length && commandId) await db.insert(placeholders).values(fields.map((field) => ({ commandId, name: field.name, label: field.label, type: field.type, required: field.required, options: JSON.stringify(field.options), defaultValue: field.defaultValue || null }))); count += 1; } catch { conflicts.push(`${command.slug}: conflito de unicidade ou dados inválidos`); } } await db.insert(imports).values({ userId: ctx.user.id, filename: input.filename, format: input.format, importedCount: count, status: conflicts.length ? "completed_with_conflicts" : "completed" }); return { success: true, importedCount: count, conflicts }; }),
  }),
});
export type AppRouter = typeof appRouter;
